In [1]:
# comprehenssion example 1
import numpy as np
a = [4,6,7,3,4]
b = [x for x in a if x > 5] 
b

[6, 7]

In [2]:
b = []
for x in a :
    if x > 5 :
        b.append(x)
b

[6, 7]

In [3]:
names = ['ch','dh','rf','ed','ef','tr']
new_names = [name for name in names if name.lower().startswith('c')]
new_names

['ch']

In [5]:
import numpy as np
A = np.random.randint(10, size=(4,4))
print(A)
max_element = [max(i) for i in A]
max_element

[[9 9 5 6]
 [2 1 1 3]
 [0 3 3 6]
 [5 7 1 3]]


[9, 3, 6, 7]

In [6]:
names = ['ch','dh','rf','ed','ef','tr']
new_names = [name for name in names 
             if name.lower.endswith('b') and len(name) > 2]
new_names


AttributeError: 'builtin_function_or_method' object has no attribute 'endswith'

In [7]:
text = [['bar','foo','rgg'],['rjh','ugr','rhf','ghfr'],['grf','rgc','set']]
text_1 = [y for x in text if len(x) > 3 for y in x]
text_1

['rjh', 'ugr', 'rhf', 'ghfr']

In [8]:
text_3 = [y.upper() for x in text if len(x) == 3 for y in x if y.startswith('f')]
text_3

['FOO']